version: '3.4'

volumes:
  postgresql-db:
    driver: local

services:
  db:
    restart: always
    image: postgres:15.1
    container_name: pleroma-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 2s
      retries: 40
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: ${PLEROMA_DB_PASSWORD}
      POSTGRES_DB: pleroma
    volumes:
      - ${PLEROMA_DB_DIR}:/var/lib/postgresql/data
      - ./pgdump:/pgdump
    ports:
      - "5432:5432"
    networks:
      - back-pleroma

  web:
    build: docker/images/otp/.
    #container_name: pleroma_web
    restart: always
    environment:
      MIX_ENV: prod
    ports:
      - '4000:4000'
    volumes:
      - ./data/pleroma/content/uploads:/var/lib/pleroma/uploads
      - ./pl.nagi.fan-custom/static:/var/lib/pleroma/static
      - ./data/pleroma/config:/etc/pleroma:rw
    depends_on:
      db:
        condition: service_healthy
      
    networks:
      - caddy
      - back-pleroma
    labels:
      caddy: ${PLEROMA_HOSTNAME}
      caddy.1_@glitch-lily.path_regexp: "^/((500.html|embed.js|logo-cybre-glitch.gif|robots.txt|oops.gif|sw.js|background-cybre.png|oops.png|web-push-icon_expand.png|badge.png|web-push-icon_favourite.png|clock.js|inert.css|riot-glitch.png|web-push-icon_reblog.png)|(web|assets|emoji|ocr|sounds|avatars|packs).*)"
      caddy.2_handle: "@glitch-lily"
      caddy.2_handle.reverse_proxy: "glitch-lily:80"
      caddy.3_handle.reverse_proxy: "web:4000"

  glitch-lily:
    image: nginx:latest
    container_name: glitch-lily
    restart: always
    tty: false
    volumes:
      - ./docker/setting/glitch-lily/templates:/etc/nginx/templates:ro
      - ./pl.nagi.fan-custom/static/frontends/glitch-lily/servant:/var/www/html:ro
    networks:
      - caddy

networks:
  caddy:
    external: true
  back-pleroma:
    external: true
